/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_danieljuarez;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danie
 */
public class Main extends javax.swing.JFrame {

    static Random random = new Random();

    public Main() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPane = new javax.swing.JDialog();
        AdminTabbedPane = new javax.swing.JTabbedPane();
        ItemsTab = new javax.swing.JPanel();
        ItemsScrollPane = new javax.swing.JScrollPane();
        TableItems = new javax.swing.JTable();
        NombreItem = new javax.swing.JLabel();
        tf_NombreItem = new javax.swing.JTextField();
        PrecioItem = new javax.swing.JLabel();
        tf_PrecioItem = new javax.swing.JTextField();
        TipoItem = new javax.swing.JLabel();
        cb_TipoItem = new javax.swing.JComboBox<>();
        GuardarItemButton = new javax.swing.JButton();
        CasaTab = new javax.swing.JPanel();
        CasaScrollPane = new javax.swing.JScrollPane();
        TableCasa = new javax.swing.JTable();
        NombreCasa = new javax.swing.JLabel();
        tf_NombreCasa = new javax.swing.JTextField();
        TamañoCasa = new javax.swing.JLabel();
        tf_TamañoCasa = new javax.swing.JTextField();
        CostoCasa = new javax.swing.JLabel();
        tf_CostoCasa = new javax.swing.JTextField();
        XCasa = new javax.swing.JLabel();
        tf_XCasa = new javax.swing.JTextField();
        YCasa = new javax.swing.JLabel();
        tf_YCasa = new javax.swing.JTextField();
        GuardarCasaButton = new javax.swing.JButton();
        PufflesTab = new javax.swing.JPanel();
        PufflesScrollPane = new javax.swing.JScrollPane();
        TablePuffles = new javax.swing.JTable();
        NombrePuffle = new javax.swing.JLabel();
        tf_NombrePuffle = new javax.swing.JTextField();
        ColorPuffle = new javax.swing.JLabel();
        CCPuffleButton = new javax.swing.JButton();
        PrecioPuffle = new javax.swing.JLabel();
        tf_PrecioPuffle = new javax.swing.JTextField();
        GuardarPuffleButton = new javax.swing.JButton();
        JuegosTab = new javax.swing.JPanel();
        JuegosScrollPane = new javax.swing.JScrollPane();
        TableJuegos = new javax.swing.JTable();
        NombreJuego = new javax.swing.JLabel();
        tf_NombreJuego = new javax.swing.JTextField();
        CostoJuego = new javax.swing.JLabel();
        tf_CostoJuego = new javax.swing.JTextField();
        RecompensaJuego = new javax.swing.JLabel();
        tf_RecompensaJuego = new javax.swing.JTextField();
        ExitoJuego = new javax.swing.JLabel();
        tf_ExitoJuego = new javax.swing.JTextField();
        GuardarJuegoButton = new javax.swing.JButton();
        PantallaAdmin = new javax.swing.JLabel();
        PinguinPane = new javax.swing.JDialog();
        PremiumButton = new javax.swing.JButton();
        UserTabbedPane = new javax.swing.JTabbedPane();
        ItemsTab1 = new javax.swing.JPanel();
        ComprarItemButton = new javax.swing.JButton();
        StockItemsScrollPane = new javax.swing.JScrollPane();
        StockTableItems = new javax.swing.JTable();
        MisItemsScrollPane = new javax.swing.JScrollPane();
        TableMisItems = new javax.swing.JTable();
        CasaTab1 = new javax.swing.JPanel();
        ComprarHouseButton = new javax.swing.JButton();
        VenderHouseButton = new javax.swing.JButton();
        StockCasasScrollPane = new javax.swing.JScrollPane();
        StockTableCasa = new javax.swing.JTable();
        MiCasaTab = new javax.swing.JPanel();
        MisPufflesScrollPane = new javax.swing.JScrollPane();
        TableMisPuffles = new javax.swing.JTable();
        StockPufflesScrollPane = new javax.swing.JScrollPane();
        TableStockPuffles = new javax.swing.JTable();
        ComprarPuffleButton = new javax.swing.JButton();
        JuegosTab1 = new javax.swing.JPanel();
        JuegosScrollPane1 = new javax.swing.JScrollPane();
        TableJuegos1 = new javax.swing.JTable();
        JugarButton = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        Userdinero = new javax.swing.JLabel();
        ClubPenguin = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        tf_Nombre = new javax.swing.JTextField();
        Contraseña = new javax.swing.JLabel();
        tf_Contraseña = new javax.swing.JTextField();
        EntrarButton = new javax.swing.JButton();

        TableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ItemsScrollPane.setViewportView(TableItems);
        if (TableItems.getColumnModel().getColumnCount() > 0) {
            TableItems.getColumnModel().getColumn(0).setResizable(false);
            TableItems.getColumnModel().getColumn(1).setResizable(false);
            TableItems.getColumnModel().getColumn(2).setResizable(false);
        }

        NombreItem.setText("Nombre");

        tf_NombreItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NombreItemActionPerformed(evt);
            }
        });

        PrecioItem.setText("Precio");

        TipoItem.setText("Tipo");

        cb_TipoItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sombreros", "Gafas", "Bufanda", "Chaqueta", "Pantalon", "Zapatos" }));
        cb_TipoItem.setSelectedIndex(-1);

        GuardarItemButton.setText("Guardar");
        GuardarItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarItemButtonMouseClicked(evt);
            }
        });
        GuardarItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ItemsTabLayout = new javax.swing.GroupLayout(ItemsTab);
        ItemsTab.setLayout(ItemsTabLayout);
        ItemsTabLayout.setHorizontalGroup(
            ItemsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemsTabLayout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addGroup(ItemsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ItemsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TipoItem)
                        .addComponent(PrecioItem)
                        .addComponent(tf_PrecioItem)
                        .addComponent(NombreItem)
                        .addComponent(tf_NombreItem)
                        .addComponent(cb_TipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GuardarItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(ItemsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemsTabLayout.createSequentialGroup()
                    .addContainerGap(99, Short.MAX_VALUE)
                    .addComponent(ItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(213, 213, 213)))
        );
        ItemsTabLayout.setVerticalGroup(
            ItemsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsTabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombreItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_NombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrecioItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_PrecioItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TipoItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_TipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(GuardarItemButton)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(ItemsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ItemsTabLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(ItemsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        AdminTabbedPane.addTab("Items", ItemsTab);

        TableCasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tamaño", "Costo", "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CasaScrollPane.setViewportView(TableCasa);
        if (TableCasa.getColumnModel().getColumnCount() > 0) {
            TableCasa.getColumnModel().getColumn(0).setResizable(false);
            TableCasa.getColumnModel().getColumn(1).setResizable(false);
            TableCasa.getColumnModel().getColumn(2).setResizable(false);
            TableCasa.getColumnModel().getColumn(3).setResizable(false);
            TableCasa.getColumnModel().getColumn(4).setResizable(false);
        }

        NombreCasa.setText("Nombre");

        tf_NombreCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NombreCasaActionPerformed(evt);
            }
        });

        TamañoCasa.setText("Tamaño");

        CostoCasa.setText("Costo");

        XCasa.setText("X");

        tf_XCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_XCasaActionPerformed(evt);
            }
        });

        YCasa.setText("Y");

        tf_YCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_YCasaActionPerformed(evt);
            }
        });

        GuardarCasaButton.setText("Guardar");
        GuardarCasaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarCasaButtonMouseClicked(evt);
            }
        });
        GuardarCasaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCasaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CasaTabLayout = new javax.swing.GroupLayout(CasaTab);
        CasaTab.setLayout(CasaTabLayout);
        CasaTabLayout.setHorizontalGroup(
            CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CasaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addGroup(CasaTabLayout.createSequentialGroup()
                        .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CasaTabLayout.createSequentialGroup()
                                .addComponent(XCasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_XCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(YCasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_YCasa))
                            .addGroup(CasaTabLayout.createSequentialGroup()
                                .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_NombreCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreCasa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_TamañoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TamañoCasa))))
                        .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CasaTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CostoCasa)
                                    .addComponent(tf_CostoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CasaTabLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(GuardarCasaButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CasaTabLayout.setVerticalGroup(
            CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CasaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCasa)
                    .addComponent(TamañoCasa)
                    .addComponent(CostoCasa))
                .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CasaTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_NombreCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_TamañoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_CostoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(XCasa)
                            .addComponent(tf_XCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YCasa)
                            .addComponent(tf_YCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CasaTabLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(GuardarCasaButton)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        AdminTabbedPane.addTab("Casa", CasaTab);

        TablePuffles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        PufflesScrollPane.setViewportView(TablePuffles);
        if (TablePuffles.getColumnModel().getColumnCount() > 0) {
            TablePuffles.getColumnModel().getColumn(0).setResizable(false);
            TablePuffles.getColumnModel().getColumn(1).setResizable(false);
            TablePuffles.getColumnModel().getColumn(2).setResizable(false);
        }

        NombrePuffle.setText("Nombre");

        ColorPuffle.setText("Color");

        CCPuffleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CCPuffleButtonMouseClicked(evt);
            }
        });

        PrecioPuffle.setText("Precio");

        GuardarPuffleButton.setText("Guardar");
        GuardarPuffleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarPuffleButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PufflesTabLayout = new javax.swing.GroupLayout(PufflesTab);
        PufflesTab.setLayout(PufflesTabLayout);
        PufflesTabLayout.setHorizontalGroup(
            PufflesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PufflesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PufflesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(PufflesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PufflesTabLayout.createSequentialGroup()
                        .addComponent(GuardarPuffleButton)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PufflesTabLayout.createSequentialGroup()
                        .addGroup(PufflesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombrePuffle)
                            .addComponent(ColorPuffle)
                            .addComponent(CCPuffleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PrecioPuffle)
                            .addComponent(tf_PrecioPuffle)
                            .addComponent(tf_NombrePuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))))
        );
        PufflesTabLayout.setVerticalGroup(
            PufflesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PufflesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PufflesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PufflesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(PufflesTabLayout.createSequentialGroup()
                        .addComponent(NombrePuffle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_NombrePuffle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(ColorPuffle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCPuffleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PrecioPuffle)
                        .addGap(4, 4, 4)
                        .addComponent(tf_PrecioPuffle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(GuardarPuffleButton)
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );

        AdminTabbedPane.addTab("Puffles", PufflesTab);

        TableJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Costo", "Recompensa", "Porcentaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JuegosScrollPane.setViewportView(TableJuegos);
        if (TableJuegos.getColumnModel().getColumnCount() > 0) {
            TableJuegos.getColumnModel().getColumn(0).setResizable(false);
            TableJuegos.getColumnModel().getColumn(1).setResizable(false);
            TableJuegos.getColumnModel().getColumn(2).setResizable(false);
            TableJuegos.getColumnModel().getColumn(3).setResizable(false);
        }

        NombreJuego.setText("Nombre");

        tf_NombreJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NombreJuegoActionPerformed(evt);
            }
        });

        CostoJuego.setText("Costo");

        RecompensaJuego.setText("Recompensa");

        ExitoJuego.setText("Posibilidad de Exito");

        GuardarJuegoButton.setText("Guardar");
        GuardarJuegoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarJuegoButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JuegosTabLayout = new javax.swing.GroupLayout(JuegosTab);
        JuegosTab.setLayout(JuegosTabLayout);
        JuegosTabLayout.setHorizontalGroup(
            JuegosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JuegosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JuegosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JuegosTabLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(GuardarJuegoButton))
                    .addComponent(NombreJuego)
                    .addComponent(CostoJuego)
                    .addComponent(RecompensaJuego)
                    .addComponent(ExitoJuego)
                    .addGroup(JuegosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tf_ExitoJuego, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addComponent(tf_RecompensaJuego, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_CostoJuego, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_NombreJuego, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JuegosTabLayout.setVerticalGroup(
            JuegosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegosTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JuegosTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JuegosTabLayout.createSequentialGroup()
                        .addComponent(JuegosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(JuegosTabLayout.createSequentialGroup()
                        .addComponent(NombreJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_NombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CostoJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_CostoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecompensaJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_RecompensaJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitoJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_ExitoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(GuardarJuegoButton)
                        .addGap(0, 94, Short.MAX_VALUE))))
        );

        AdminTabbedPane.addTab("Juegos", JuegosTab);

        PantallaAdmin.setText("Pantalla de Administracion");

        javax.swing.GroupLayout AdminPaneLayout = new javax.swing.GroupLayout(AdminPane.getContentPane());
        AdminPane.getContentPane().setLayout(AdminPaneLayout);
        AdminPaneLayout.setHorizontalGroup(
            AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPaneLayout.createSequentialGroup()
                        .addComponent(PantallaAdmin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AdminTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                .addContainerGap())
        );
        AdminPaneLayout.setVerticalGroup(
            AdminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PantallaAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminTabbedPane)
                .addGap(12, 12, 12))
        );

        PremiumButton.setText("Premium");
        PremiumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PremiumButtonMouseClicked(evt);
            }
        });

        ComprarItemButton.setText("Comprar");
        ComprarItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarItemButtonMouseClicked(evt);
            }
        });
        ComprarItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarItemButtonActionPerformed(evt);
            }
        });

        StockTableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockItemsScrollPane.setViewportView(StockTableItems);
        if (StockTableItems.getColumnModel().getColumnCount() > 0) {
            StockTableItems.getColumnModel().getColumn(0).setResizable(false);
            StockTableItems.getColumnModel().getColumn(1).setResizable(false);
            StockTableItems.getColumnModel().getColumn(2).setResizable(false);
        }

        TableMisItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MisItemsScrollPane.setViewportView(TableMisItems);
        if (TableMisItems.getColumnModel().getColumnCount() > 0) {
            TableMisItems.getColumnModel().getColumn(0).setResizable(false);
            TableMisItems.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout ItemsTab1Layout = new javax.swing.GroupLayout(ItemsTab1);
        ItemsTab1.setLayout(ItemsTab1Layout);
        ItemsTab1Layout.setHorizontalGroup(
            ItemsTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsTab1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MisItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ItemsTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StockItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ComprarItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addContainerGap())
        );
        ItemsTab1Layout.setVerticalGroup(
            ItemsTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemsTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ItemsTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MisItemsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGroup(ItemsTab1Layout.createSequentialGroup()
                        .addComponent(ComprarItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StockItemsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        UserTabbedPane.addTab("Items", ItemsTab1);

        ComprarHouseButton.setText("Comprar");
        ComprarHouseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarHouseButtonMouseClicked(evt);
            }
        });

        VenderHouseButton.setText("Vender");
        VenderHouseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VenderHouseButtonMouseClicked(evt);
            }
        });

        StockTableCasa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tamaño", "Costo", "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockCasasScrollPane.setViewportView(StockTableCasa);
        if (StockTableCasa.getColumnModel().getColumnCount() > 0) {
            StockTableCasa.getColumnModel().getColumn(0).setResizable(false);
            StockTableCasa.getColumnModel().getColumn(1).setResizable(false);
            StockTableCasa.getColumnModel().getColumn(2).setResizable(false);
            StockTableCasa.getColumnModel().getColumn(3).setResizable(false);
            StockTableCasa.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout CasaTab1Layout = new javax.swing.GroupLayout(CasaTab1);
        CasaTab1.setLayout(CasaTab1Layout);
        CasaTab1Layout.setHorizontalGroup(
            CasaTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasaTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CasaTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StockCasasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(CasaTab1Layout.createSequentialGroup()
                        .addComponent(ComprarHouseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VenderHouseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CasaTab1Layout.setVerticalGroup(
            CasaTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasaTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CasaTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComprarHouseButton)
                    .addComponent(VenderHouseButton))
                .addGap(15, 15, 15)
                .addComponent(StockCasasScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        UserTabbedPane.addTab("Casa", CasaTab1);

        TableMisPuffles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MisPufflesScrollPane.setViewportView(TableMisPuffles);
        if (TableMisPuffles.getColumnModel().getColumnCount() > 0) {
            TableMisPuffles.getColumnModel().getColumn(0).setResizable(false);
            TableMisPuffles.getColumnModel().getColumn(1).setResizable(false);
        }

        TableStockPuffles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Color", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockPufflesScrollPane.setViewportView(TableStockPuffles);
        if (TableStockPuffles.getColumnModel().getColumnCount() > 0) {
            TableStockPuffles.getColumnModel().getColumn(0).setResizable(false);
            TableStockPuffles.getColumnModel().getColumn(1).setResizable(false);
            TableStockPuffles.getColumnModel().getColumn(2).setResizable(false);
        }

        ComprarPuffleButton.setText("Comprar");
        ComprarPuffleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComprarPuffleButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MiCasaTabLayout = new javax.swing.GroupLayout(MiCasaTab);
        MiCasaTab.setLayout(MiCasaTabLayout);
        MiCasaTabLayout.setHorizontalGroup(
            MiCasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiCasaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MisPufflesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MiCasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StockPufflesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ComprarPuffleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                .addContainerGap())
        );
        MiCasaTabLayout.setVerticalGroup(
            MiCasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiCasaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MiCasaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiCasaTabLayout.createSequentialGroup()
                        .addComponent(ComprarPuffleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StockPufflesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(MisPufflesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addContainerGap())
        );

        UserTabbedPane.addTab("Mi Casa", MiCasaTab);

        TableJuegos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Costo", "Recompensa", "Porcentaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JuegosScrollPane1.setViewportView(TableJuegos1);
        if (TableJuegos1.getColumnModel().getColumnCount() > 0) {
            TableJuegos1.getColumnModel().getColumn(0).setResizable(false);
            TableJuegos1.getColumnModel().getColumn(1).setResizable(false);
            TableJuegos1.getColumnModel().getColumn(2).setResizable(false);
            TableJuegos1.getColumnModel().getColumn(3).setResizable(false);
        }

        JugarButton.setText("Jugar");
        JugarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JugarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JuegosTab1Layout = new javax.swing.GroupLayout(JuegosTab1);
        JuegosTab1.setLayout(JuegosTab1Layout);
        JuegosTab1Layout.setHorizontalGroup(
            JuegosTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JuegosTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JuegosTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JuegosScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(JuegosTab1Layout.createSequentialGroup()
                        .addComponent(JugarButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JuegosTab1Layout.setVerticalGroup(
            JuegosTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JuegosTab1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JugarButton)
                .addGap(18, 18, 18)
                .addComponent(JuegosScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        UserTabbedPane.addTab("Juegos", JuegosTab1);

        Username.setText("Pinguino Usuario");

        Userdinero.setText("Dinero");

        javax.swing.GroupLayout PinguinPaneLayout = new javax.swing.GroupLayout(PinguinPane.getContentPane());
        PinguinPane.getContentPane().setLayout(PinguinPaneLayout);
        PinguinPaneLayout.setHorizontalGroup(
            PinguinPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinguinPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Userdinero)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PinguinPaneLayout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(PremiumButton)
                .addGap(161, 161, 161))
            .addGroup(PinguinPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PinguinPaneLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(UserTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );
        PinguinPaneLayout.setVerticalGroup(
            PinguinPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PinguinPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PinguinPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(Userdinero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(PremiumButton)
                .addContainerGap())
            .addGroup(PinguinPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PinguinPaneLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(UserTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClubPenguin.setText("Club Penguin");

        Nombre.setText("Nombre");

        Contraseña.setText("Contraseña");

        EntrarButton.setText("Entrar");
        EntrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ClubPenguin)
                    .addComponent(Nombre)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contraseña)
                    .addComponent(tf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntrarButton))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(ClubPenguin)
                .addGap(38, 38, 38)
                .addComponent(Nombre)
                .addGap(11, 11, 11)
                .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(EntrarButton)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarButtonMouseClicked
        if (tf_Nombre.getText().equals(useradmin) && tf_Contraseña.getText().equals(passwordadmin)) {
            JOptionPane.showMessageDialog(this, "LogIn", "Bienvenido Admin", JOptionPane.PLAIN_MESSAGE);
            tf_Nombre.setText("");
            tf_Contraseña.setText("");
            AdminPane.setModal(true);
            AdminPane.pack();
            AdminPane.setLocationRelativeTo(this);
            AdminPane.setVisible(true);
        } else {
            boolean existe = false;
            for (int i = 0; i < Users.size(); i++) {
                if (tf_Nombre.getText().equals(Users.get(i).getNombrePinguino())) {
                    existe = true;
                }
            }
            if (existe) {
                for (int i = 0; i < Users.size(); i++) {
                    if (tf_Nombre.getText().equals(Users.get(i).getNombrePinguino()) && tf_Contraseña.getText().equals(Users.get(i).getContraseñaPinguino())) {
                        Using = Users.get(i);
                    }
                }

                TableMisItems.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre", "Tipo"
                        }
                ) {
                    Class[] types = new Class[]{
                        java.lang.String.class, java.lang.Object.class
                    };
                    boolean[] canEdit = new boolean[]{
                        false, false,};
                });

                DefaultTableModel modelo
                        = (DefaultTableModel) TableMisItems.getModel();
                for (int i = 0; i < Using.ItemsPinguino.size(); i++) {
                    Object[] newrow = {
                        Using.ItemsPinguino.get(i).getNombreItem(),
                        Using.ItemsPinguino.get(i).getTipoItem()
                    };
                    modelo.addRow(newrow);
                    TableMisItems.setModel(modelo);
                }

                Username.setText("Pinguino " + Using.NombrePinguino);
                Userdinero.setText("Dinero: " + Using.DineroPinguino);
                JOptionPane.showMessageDialog(this, "Bienvenido de Vuelta " + Using.getNombrePinguino(), "LogIn", JOptionPane.PLAIN_MESSAGE);
                tf_Nombre.setText("");
                tf_Contraseña.setText("");
                PinguinPane.setModal(true);
                PinguinPane.pack();
                PinguinPane.setLocationRelativeTo(this);
                PinguinPane.setVisible(true);
                return;
            } else {

                TableMisItems.setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][]{},
                        new String[]{
                            "Nombre", "Tipo"
                        }
                ) {
                    Class[] types = new Class[]{
                        java.lang.String.class, java.lang.Object.class
                    };
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false
                    };

                    public Class getColumnClass(int columnIndex) {
                        return types[columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit[columnIndex];
                    }
                });

                Pinguino np = new Pinguino(tf_Nombre.getText(), tf_Contraseña.getText(), false, 1000, new Casa());
                Users.add(np);
                Using = np;
                Username.setText("Pinguino " + Using.NombrePinguino);
                Userdinero.setText("Dinero: " + Using.DineroPinguino);
                JOptionPane.showMessageDialog(this, "Bienvenido " + Using.getNombrePinguino(), "LogIn", JOptionPane.PLAIN_MESSAGE);
                tf_Nombre.setText("");
                tf_Contraseña.setText("");
                PinguinPane.setModal(true);
                PinguinPane.pack();
                PinguinPane.setLocationRelativeTo(this);
                PinguinPane.setVisible(true);
            }
        }
    }//GEN-LAST:event_EntrarButtonMouseClicked

    private void GuardarItemButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarItemButtonMouseClicked
        String NombreItem = tf_NombreItem.getText();
        int PrecioItem = Integer.parseInt(tf_PrecioItem.getText());
        String TipoItem = cb_TipoItem.getSelectedItem().toString();
        Item i = new Item(NombreItem, PrecioItem, TipoItem);
        Items.add(i);
        Object[] newrow = {
            i.getNombreItem(),
            i.getPrecioItem(),
            i.getTipoItem()
        };
        DefaultTableModel modelo
                = (DefaultTableModel) TableItems.getModel();
        modelo.addRow(newrow);
        TableItems.setModel(modelo);
        StockTableItems.setModel(modelo);

        tf_NombreItem.setText("");
        tf_PrecioItem.setText("");
        cb_TipoItem.setSelectedItem(-1);

    }//GEN-LAST:event_GuardarItemButtonMouseClicked

    private void tf_NombreCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NombreCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NombreCasaActionPerformed

    private void tf_XCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_XCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_XCasaActionPerformed

    private void tf_YCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_YCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_YCasaActionPerformed

    private void GuardarCasaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCasaButtonMouseClicked

        String NombreCasa = tf_NombreCasa.getText();
        String TamañoCasa = tf_TamañoCasa.getText();
        int CostoCasa = Integer.parseInt(tf_CostoCasa.getText());
        int xCasa = Integer.parseInt(tf_XCasa.getText());
        int yCasa = Integer.parseInt(tf_YCasa.getText());

        Casa c = new Casa(NombreCasa, TamañoCasa, CostoCasa, xCasa, yCasa);
        Casas.add(c);
        Object[] newrow = {
            c.getNombreCasa(),
            c.getTamañoCasa(),
            c.getCostoCasa(),
            c.getCooXCasa(),
            c.getCooYCasa()
        };
        DefaultTableModel modelo
                = (DefaultTableModel) TableCasa.getModel();
        modelo.addRow(newrow);
        TableCasa.setModel(modelo);
        StockTableCasa.setModel(modelo);

        tf_NombreCasa.setText("");
        tf_TamañoCasa.setText("");
        tf_CostoCasa.setText("");
        tf_XCasa.setText("");
        tf_YCasa.setText("");

    }//GEN-LAST:event_GuardarCasaButtonMouseClicked

    private void GuardarPuffleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarPuffleButtonMouseClicked
        String PuffleNombre = tf_NombrePuffle.getText();
        Color ColorPuffle = CCPuffleButton.getBackground();
        int PrecioPuffle = Integer.parseInt(tf_PrecioPuffle.getText());

        Puffle p = new Puffle(PuffleNombre, PrecioPuffle, ColorPuffle);
        Puffles.add(p);
        Object[] newrow = {
            p.getNombrePuffle(),
            p.getColorPuffle(),
            p.getPrecioPuffle()
        };
        DefaultTableModel modelo
                = (DefaultTableModel) TablePuffles.getModel();
        modelo.addRow(newrow);
        TablePuffles.setModel(modelo);
        TableStockPuffles.setModel(modelo);
        tf_NombrePuffle.setText("");
        CCPuffleButton.setBackground(null);
        tf_PrecioPuffle.setText("");

    }//GEN-LAST:event_GuardarPuffleButtonMouseClicked

    private void CCPuffleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CCPuffleButtonMouseClicked
        CCPuffleButton.setBackground(JColorChooser.showDialog(rootPane, "Seleccione un Color", Color.yellow));
    }//GEN-LAST:event_CCPuffleButtonMouseClicked

    private void GuardarJuegoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarJuegoButtonMouseClicked

        String JuegoNombre = tf_NombreJuego.getText();
        int JuegoCosto = Integer.parseInt(tf_CostoJuego.getText());
        int JuegoRecompensa = Integer.parseInt(tf_RecompensaJuego.getText());
        int JuegoExito = Integer.parseInt(tf_ExitoJuego.getText());
        Object[] newrow = {
            JuegoNombre,
            JuegoCosto,
            JuegoRecompensa,
            JuegoExito
        };
        DefaultTableModel modelo
                = (DefaultTableModel) TableJuegos.getModel();
        modelo.addRow(newrow);
        TableJuegos.setModel(modelo);
        TableJuegos1.setModel(modelo);
        tf_NombreJuego.setText("");
        tf_CostoJuego.setText("");
        tf_RecompensaJuego.setText("");
        tf_ExitoJuego.setText("");

    }//GEN-LAST:event_GuardarJuegoButtonMouseClicked

    private void tf_NombreItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NombreItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NombreItemActionPerformed

    private void ComprarItemButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarItemButtonMouseClicked
        if (StockTableItems.getSelectedRow() >= 0) {
//            DefaultTableModel modelostock
//                    = (DefaultTableModel) StockTableItems.getModel();
            if ((int) StockTableItems.getValueAt(StockTableItems.getSelectedRow(), 1) > Using.DineroPinguino) {
                JOptionPane.showMessageDialog(rootPane, "No Hubo Compra. Dinero Insuficiente");
            } else {
                DefaultTableModel modelo
                        = (DefaultTableModel) TableMisItems.getModel();
                int resta = (int) StockTableItems.getValueAt(StockTableItems.getSelectedRow(), 1);
                Using.DineroPinguino = Using.DineroPinguino - resta;
                Userdinero.setText("Dinero: " + Using.DineroPinguino);
                Object[] newrow = {
                    StockTableItems.getValueAt(StockTableItems.getSelectedRow(), 0),
                    StockTableItems.getValueAt(StockTableItems.getSelectedRow(), 1)
                };
                modelo.addRow(newrow);
                TableMisItems.setModel(modelo);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No Hubo Compra");
        }
    }//GEN-LAST:event_ComprarItemButtonMouseClicked

    private void GuardarItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarItemButtonActionPerformed

    private void GuardarCasaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCasaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarCasaButtonActionPerformed

    private void PremiumButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PremiumButtonMouseClicked
        if (Using.getDineroPinguino() < 2000) {
            JOptionPane.showMessageDialog(rootPane, "No Cuenta Con El Dinero Suficiente");
        } else {
            Using.DineroPinguino = Using.DineroPinguino - 2000;
            Using.setSocioPinguino(true);
            JOptionPane.showMessageDialog(rootPane, "Felicidades! Ahora Es Premium");
        }
    }//GEN-LAST:event_PremiumButtonMouseClicked

    private void ComprarHouseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarHouseButtonMouseClicked
        if (StockTableCasa.getSelectedRow() >= 0) {
            if (Using.SocioPinguino == true) {
                if ((int) StockTableCasa.getValueAt(StockTableCasa.getSelectedRow(), 2) > Using.DineroPinguino) {
                    JOptionPane.showMessageDialog(rootPane, "No Hubo Compra. Dinero Insuficiente");
                } else {
////            DefaultTableModel modelostock
////                    = (DefaultTableModel) StockTableItems.getModel();
                    int resta = (int) StockTableCasa.getValueAt(StockTableCasa.getSelectedRow(), 2);
                    Using.DineroPinguino = Using.DineroPinguino - resta;
                    Userdinero.setText("Dinero: " + Using.DineroPinguino);
                    Using.CasaPinguino.setNombreCasa((String) StockTableCasa.getValueAt(StockTableCasa.getSelectedRow(), 0));
                    Using.CasaPinguino.setTamañoCasa((String) StockTableCasa.getValueAt(StockTableCasa.getSelectedRow(), 1));
                    Using.CasaPinguino.setCostoCasa((int) StockTableCasa.getValueAt(StockTableCasa.getSelectedRow(), 2));
                    Using.CasaPinguino.setCooXCasa((int) StockTableCasa.getValueAt(StockTableCasa.getSelectedRow(), 3));
                    Using.CasaPinguino.setCooYCasa((int) StockTableCasa.getValueAt(StockTableCasa.getSelectedRow(), 4));
//            modelostock.removeRow(StockTableCasa.getSelectedRow());
//            StockTableCasa.setModel(modelostock);
                }
            } else {
                if ((int)StockTableCasa.getValueAt(StockTableCasa.getSelectedRow(), 2) > 200) {
                    JOptionPane.showMessageDialog(rootPane, "No Puede Comprar Casas Mayores a 200m^2, Upgrade a Premium");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No Hubo Compra");
        }
    }//GEN-LAST:event_ComprarHouseButtonMouseClicked

    private void VenderHouseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderHouseButtonMouseClicked
        if (StockTableCasa.getSelectedRow() >= 0) {
            int cant = 0;
            cant += Using.getCasaPinguino().CostoCasa;
            for (int i = 0; i < Using.getCasaPinguino().getPufflesCasa().size(); i++) {
                cant += Using.getCasaPinguino().getPufflesCasa().get(i).PrecioPuffle;
            }
            Using.DineroPinguino += cant;
            Userdinero.setText("Dinero: " + Using.DineroPinguino);
            Casa c = new Casa(Using.CasaPinguino.NombreCasa, Using.CasaPinguino.TamañoCasa, Using.CasaPinguino.CostoCasa, Using.CasaPinguino.CooXCasa, Using.CasaPinguino.CooYCasa);
            Casas.add(c);
            Object[] newrow = {
                c.getNombreCasa(),
                c.getTamañoCasa(),
                c.getCostoCasa(),
                c.getCooXCasa(),
                c.getCooYCasa()
            };
            DefaultTableModel modelo
                    = (DefaultTableModel) TableCasa.getModel();
            modelo.addRow(newrow);
            TableCasa.setModel(modelo);
            StockTableCasa.setModel(modelo);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No Hubo Venta");
        }
    }//GEN-LAST:event_VenderHouseButtonMouseClicked

    private void ComprarPuffleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComprarPuffleButtonMouseClicked
        if (TableStockPuffles.getSelectedRow() >= 0) {

            if (Using.SocioPinguino == true) {
                if ((int) TableStockPuffles.getValueAt(TableStockPuffles.getSelectedRow(), 2) > Using.DineroPinguino) {
                    JOptionPane.showMessageDialog(rootPane, "No Hubo Compra. Dinero Insuficiente");
                } else {
//            DefaultTableModel modelostock
//                    = (DefaultTableModel) StockTableItems.getModel();
                    DefaultTableModel modelo
                            = (DefaultTableModel) TableMisPuffles.getModel();
                    int resta = (int) TableStockPuffles.getValueAt(TableStockPuffles.getSelectedRow(), 2);
                    Using.DineroPinguino = Using.DineroPinguino - resta;
                    Userdinero.setText("Dinero: " + Using.DineroPinguino);
                    Object[] newrow = {
                        TableStockPuffles.getValueAt(TableStockPuffles.getSelectedRow(), 0),
                        TableStockPuffles.getValueAt(TableStockPuffles.getSelectedRow(), 1)
                    };
                    modelo.addRow(newrow);
                    TableMisPuffles.setModel(modelo);
                }
            } else {
                if (Using.CasaPinguino.PufflesCasa.size() == 2) {
                    JOptionPane.showMessageDialog(rootPane, "Ya No Puede Comprar Más Puffles, Upgrade a Premium");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No Hubo Compra");
        }
    }//GEN-LAST:event_ComprarPuffleButtonMouseClicked

    private void JugarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JugarButtonMouseClicked
        if (TableJuegos1.getSelectedRow() >= 0) {
            int numero = 0 + random.nextInt(100);
            int resta = (int) TableJuegos1.getValueAt(TableJuegos1.getSelectedRow(), 1);
            Using.DineroPinguino = Using.DineroPinguino - resta;
            Userdinero.setText("Dinero: " + Using.DineroPinguino);
            if (numero < (int) TableJuegos1.getValueAt(TableJuegos1.getSelectedRow(), 3)) {
                JOptionPane.showMessageDialog(rootPane, "Ganó!" + TableJuegos1.getValueAt(TableJuegos1.getSelectedRow(), 2));
                int suma = (int) TableJuegos1.getValueAt(TableJuegos1.getSelectedRow(), 2);
                Using.DineroPinguino = Using.DineroPinguino + suma;
                Userdinero.setText("Dinero: " + Using.DineroPinguino);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Perdió!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No Hay Juegos Disponibles");
        }

    }//GEN-LAST:event_JugarButtonMouseClicked

    private void tf_NombreJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NombreJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NombreJuegoActionPerformed

    private void ComprarItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComprarItemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AdminPane;
    private javax.swing.JTabbedPane AdminTabbedPane;
    private javax.swing.JButton CCPuffleButton;
    private javax.swing.JScrollPane CasaScrollPane;
    private javax.swing.JPanel CasaTab;
    private javax.swing.JPanel CasaTab1;
    private javax.swing.JLabel ClubPenguin;
    private javax.swing.JLabel ColorPuffle;
    private javax.swing.JButton ComprarHouseButton;
    private javax.swing.JButton ComprarItemButton;
    private javax.swing.JButton ComprarPuffleButton;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel CostoCasa;
    private javax.swing.JLabel CostoJuego;
    private javax.swing.JButton EntrarButton;
    private javax.swing.JLabel ExitoJuego;
    private javax.swing.JButton GuardarCasaButton;
    private javax.swing.JButton GuardarItemButton;
    private javax.swing.JButton GuardarJuegoButton;
    private javax.swing.JButton GuardarPuffleButton;
    private javax.swing.JScrollPane ItemsScrollPane;
    private javax.swing.JPanel ItemsTab;
    private javax.swing.JPanel ItemsTab1;
    private javax.swing.JScrollPane JuegosScrollPane;
    private javax.swing.JScrollPane JuegosScrollPane1;
    private javax.swing.JPanel JuegosTab;
    private javax.swing.JPanel JuegosTab1;
    private javax.swing.JButton JugarButton;
    private javax.swing.JPanel MiCasaTab;
    private javax.swing.JScrollPane MisItemsScrollPane;
    private javax.swing.JScrollPane MisPufflesScrollPane;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreCasa;
    private javax.swing.JLabel NombreItem;
    private javax.swing.JLabel NombreJuego;
    private javax.swing.JLabel NombrePuffle;
    private javax.swing.JLabel PantallaAdmin;
    private javax.swing.JDialog PinguinPane;
    private javax.swing.JLabel PrecioItem;
    private javax.swing.JLabel PrecioPuffle;
    private javax.swing.JButton PremiumButton;
    private javax.swing.JScrollPane PufflesScrollPane;
    private javax.swing.JPanel PufflesTab;
    private javax.swing.JLabel RecompensaJuego;
    private javax.swing.JScrollPane StockCasasScrollPane;
    private javax.swing.JScrollPane StockItemsScrollPane;
    private javax.swing.JScrollPane StockPufflesScrollPane;
    private javax.swing.JTable StockTableCasa;
    private javax.swing.JTable StockTableItems;
    private javax.swing.JTable TableCasa;
    private javax.swing.JTable TableItems;
    private javax.swing.JTable TableJuegos;
    private javax.swing.JTable TableJuegos1;
    private javax.swing.JTable TableMisItems;
    private javax.swing.JTable TableMisPuffles;
    private javax.swing.JTable TablePuffles;
    private javax.swing.JTable TableStockPuffles;
    private javax.swing.JLabel TamañoCasa;
    private javax.swing.JLabel TipoItem;
    private javax.swing.JTabbedPane UserTabbedPane;
    private javax.swing.JLabel Userdinero;
    private javax.swing.JLabel Username;
    private javax.swing.JButton VenderHouseButton;
    private javax.swing.JLabel XCasa;
    private javax.swing.JLabel YCasa;
    private javax.swing.JComboBox<String> cb_TipoItem;
    private javax.swing.JTextField tf_Contraseña;
    private javax.swing.JTextField tf_CostoCasa;
    private javax.swing.JTextField tf_CostoJuego;
    private javax.swing.JTextField tf_ExitoJuego;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_NombreCasa;
    private javax.swing.JTextField tf_NombreItem;
    private javax.swing.JTextField tf_NombreJuego;
    private javax.swing.JTextField tf_NombrePuffle;
    private javax.swing.JTextField tf_PrecioItem;
    private javax.swing.JTextField tf_PrecioPuffle;
    private javax.swing.JTextField tf_RecompensaJuego;
    private javax.swing.JTextField tf_TamañoCasa;
    private javax.swing.JTextField tf_XCasa;
    private javax.swing.JTextField tf_YCasa;
    // End of variables declaration//GEN-END:variables
    ArrayList<Pinguino> Users = new ArrayList();
    ArrayList<Item> Items = new ArrayList();
    ArrayList<Casa> Casas = new ArrayList();
    ArrayList<Puffle> Puffles = new ArrayList();
    String useradmin = "p", passwordadmin = "p";
    Pinguino Using;

}
